spring.application.name=server

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.address=0.0.0.0
jwt.secret=${JWT_SECRET:DauAnCuaNhaTroQuangSieuBaoMatKhongTheBiHackerPhaDuoc123!!!}
jwt.expiration=86400000
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:*}
oauth2.redirect.uri=${OAUTH2_REDIRECT_URI:http://localhost:5173/oauth2/redirect}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=345041378064-b86ol6lkr747755ncjqpi6n63d2fuo5e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:mock_secret}
spring.security.oauth2.client.registration.google.scope=profile,email


# Spring Mail SMTP Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quang1532006@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD:mock_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
